repos:
  - repo: local
    hooks:
      - id: clippy
        name: Clippy
        types: [rust]
        language: system
        entry: cargo +nightly clippy --all-features -- -D warnings
        pass_filenames: false
      - id: rustfmt
        name: Rust Format
        types: [rust]
        language: system
        entry: cargo fmt --all
        pass_filenames: false
      - id: cargo-check
        name: Cargo Check
        types: [rust]
        language: system
        entry: cargo check
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix, lf]
