[package]
name = "worker-app"
version = "0.1.0"
authors = ["David Herberth <github@dav1d.de>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
debug = []

[dependencies]
tmm = { path = "../tmm/" }
worker.workspace = true
cfg-if.workspace = true
anyhow = "1"
